version: 1 # version of the logfile but only 1 is available
formatters:
  console_formatter:
    format: '[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  file_formatter:
    format: '[%(asctime)s] [%(name)s] [%(levelname)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    level   : DEBUG
    formatter: console_formatter
    stream  : ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: file_formatter
    filename: ../logs/yamltestlog.log
loggers:
  server:
    level: DEBUG
    handlers: [console, file]
    propagate: no
    encoding: 'utf-8'
  src.app:
    level: DEBUG
    handlers: [console, file]
    propagate: no
    encoding: 'utf-8'
  src.app.server:
    level: DEBUG
    handlers: [ console, file ]
    propagate: no
    encoding: 'utf-8'
root:
  level: DEBUG
  handlers: [console, file]
